;; Test-only bounded actions appended to the full current vault.
(define-map context (string-ascii 100) {called: uint})
(define-private (update-context (name (string-ascii 100)) (called uint))
 (ok (map-set context name {called: called})))
(define-public (rv-donate (raw uint))
 (contract-call? .mock-ft mint (+ u1 (mod raw u1000000)) current-contract))
(define-public (rv-treasury (raw uint))
 (contract-call? .mock-ft mint (+ u1 (mod raw u1000000)) .mock-treasury))
(define-public (rv-fund-router (raw uint))
 (stx-transfer? (+ u1 (mod raw u1000000000)) tx-sender .mock-router))
(define-public (rv-world (raw uint))
 (begin
 (try! (contract-call? .mock-dia set-stale (is-eq (mod raw u7) u0)))
 (try! (contract-call? .mock-dia set-failed (is-eq (mod raw u11) u0)))
 (try! (contract-call? .mock-native set-failed (is-eq (mod raw u13) u0)))
 (try! (contract-call? .mock-native set-mid (if (is-eq (mod raw u17) u0) u0 u32000000000000)))
 (contract-call? .mock-dia set-skew (+ u8000 (mod raw u5000)))))
(define-public (rv-admin (action uint) (raw uint))
 (begin (try! (is-dao-or-extension))
 (let ((a (mod action u11)) (amount (+ u1 (mod raw u1000000))))
  (if (is-eq a u0) (begin (try! (set-window-blocks (mod raw u1009))) true)
  (if (is-eq a u1) (begin (try! (set-no-pyth-slippage-bps (mod raw u5001))) true)
  (if (is-eq a u2) (begin (try! (router-swap-split-dia amount amount u0 u0)) true)
  (if (is-eq a u3) (begin (try! (dao-recall-sbtc)) true)
  (if (is-eq a u4) (begin (try! (dao-reclaim)) true)
  (if (is-eq a u5) (begin (try! (jing-refloor 0x)) true)
  (if (is-eq a u6) (begin (try! (jing-take amount 0x)) true)
  (if (is-eq a u7) (begin (try! (router-swap-split amount u0 amount u0 u0 0x)) true)
  (if (is-eq a u8) (begin (try! (set-leeway-bps (mod raw u1001))) true)
  (if (is-eq a u9) (begin (try! (set-slippage-bps (mod raw u1001))) true)
   (begin (try! (set-router-cooldown (mod raw u145))) true)))))))))))
 (ok true))))
;; Real production setters can release the patience window in CityCoins.
(define-public (rv-batch (raw uint))
 (begin (try! (is-dao-or-extension))
 (try! (set-window-blocks u0)) (try! (set-router-cooldown u0))
 (try! (set-max-chunk-sats MAX_CHUNK_SATS)) (try! (set-no-pyth-slippage-bps u5000))
 (if (> (unwrap-panic (contract-call? .mock-ft get-balance .mock-treasury)) u0)
  (begin (try! (fund-from-treasury)) true)
  (if (is-none (var-get batch-start))
   (begin (try! (contract-call? .mock-ft mint (+ u1 (mod raw u10000)) .mock-treasury))
    (try! (fund-from-treasury)) true) true))
 (let ((amount (sbtc-balance)))
  (try! (stx-transfer? (* amount u3200) tx-sender .mock-router))
  (try! (router-swap-split-dia amount amount u0 u0)))
 (fuel-fair-book)))
(define-read-only (invariant-window-exclusive)
 (not (and (window-open) (window-elapsed))))
(define-read-only (invariant-no-clock-no-window)
 (or (is-some (var-get batch-start)) (and (not (window-open)) (not (window-elapsed)))))
(define-read-only (invariant-clock-not-future)
 (match (var-get batch-start) s (<= s burn-block-height) true))
(define-read-only (invariant-cooldown-not-future)
 (<= (var-get last-router-swap) burn-block-height))
(define-read-only (invariant-config-bounded)
 (and (<= (var-get window-blocks) MAX_WINDOW_BLOCKS)
 (<= (var-get no-pyth-slippage-bps) MAX_NO_PYTH_SLIPPAGE_BPS)
 (<= (var-get leeway-bps) MAX_LEEWAY_BPS) (<= (var-get slippage-bps) MAX_SLIPPAGE_BPS)
 (<= (var-get dia-band-bps) MAX_DIA_BAND_BPS)
 (> (var-get max-chunk-sats) u0) (<= (var-get max-chunk-sats) MAX_CHUNK_SATS)
 (<= (var-get router-cooldown-blocks) MAX_COOLDOWN_BLOCKS)))
(define-read-only (invariant-emergency-floor)
 (match (get-no-pyth-price)
  price (and (> (get limit price) u0) (<= (get limit price) (get mid price))
  (if (is-eq (get source price) "native")
   (is-eq (get limit price) (/ (get mid price) u2))
   (is-eq (get limit price) (/ (* (get mid price) (- BPS_PRECISION (var-get no-pyth-slippage-bps))) BPS_PRECISION))))
  code true))
(define-read-only (invariant-resting-peg)
 (or (is-eq (+ (contract-call? .v6-market get-token-x-deposit (contract-call? .v6-market get-current-cycle) current-contract)
 (contract-call? .v6-market get-token-x-parked current-contract)) u0)
 (let ((o (contract-call? .v6-market get-token-x-order current-contract)))
 (and (> (get limit o) u0) (is-eq (get spread-bps o) (some u0))))))
(define-read-only (invariant-ft-conservation)
 (is-eq (unwrap-panic (contract-call? .mock-ft get-total-supply))
 (+ (unwrap-panic (contract-call? .mock-ft get-balance current-contract))
 (unwrap-panic (contract-call? .mock-ft get-balance .mock-treasury))
 (unwrap-panic (contract-call? .mock-ft get-balance .v6-market))
 (unwrap-panic (contract-call? .mock-ft get-balance .mock-router)))))
